# Generated by Django 4.0 on 2021-12-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(blank=True, default='', null=True, upload_to='gallery')),
                ('Name', models.CharField(max_length=20)),
                ('Model', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='signup',
            name='Age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Password',
            field=models.CharField(default='', max_length=8),
        ),
    ]
