# Generated by Django 4.0 on 2021-12-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_gallery_alter_signup_age_alter_signup_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='Photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media'),
        ),
    ]
