# Generated by Django 4.0 on 2021-12-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_gallery_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='Photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/'),
        ),
    ]
